package InterfazUsuario;

import Basedatos.CRUD;
import Basedatos.SQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;

public class InformeUI extends javax.swing.JFrame {

    CRUD crud;
    ArrayList<Integer> idventas;

    public InformeUI() {
        initComponents();
        this.crud = new CRUD();
        this.idventas = new ArrayList();

        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_idVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Info_ventas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ImgLogoSoftware = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Id Venta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 232, 139, 30));

        txt_idVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_idVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 271, 260, 30));

        tabla_Info_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_Info_ventas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 820, 390));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Mostrar todo");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 230, 35));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("Regresar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 498, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Informes de ventas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 610, 90));

        ImgLogoSoftware.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgLogoSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo del software sin nombre.png"))); // NOI18N
        jPanel1.add(ImgLogoSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 228, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 1404, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idVentaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        mostrarInformesVenta();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.limpiarTabla();
        DefaultTableModel modelo = (DefaultTableModel) this.tabla_Info_ventas.getModel();

        modelo.setColumnCount(0);
        modelo.addColumn("Id Venta");
        modelo.addColumn("Total");
        modelo.addColumn("Fecha");

        try {
            ResultSet resultado = this.crud.seleccionar("SELECT * FROM venta_padre");
            if (resultado == null) {
                JOptionPane.showMessageDialog(null, "No se pudo ejecutar la consulta");
                return;
            }

            while (resultado.next()) {
                Object[] depAux = {
                    resultado.getInt(1),
                    resultado.getFloat(3),
                    resultado.getTimestamp(2)
                };
                modelo.addRow(depAux);
            }

            this.tabla_Info_ventas.setModel(modelo);

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No hay datos en la tabla");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la consulta: " + e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        MenuGaly menu = new MenuGaly();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLogoSoftware;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_Info_ventas;
    private javax.swing.JTextField txt_idVenta;
    // End of variables declaration//GEN-END:variables
    private void mostrarInformesVenta() {

        this.limpiarTabla();

        DefaultTableModel modelo = (DefaultTableModel) this.tabla_Info_ventas.getModel();

        modelo.addColumn("Id Venta");
        modelo.addColumn("Total");
        modelo.addColumn("Fecha");

        String codigoBuscar = this.txt_idVenta.getText();

        try {
            int idVenta = Integer.parseInt(codigoBuscar.trim());
            ResultSet resultado = this.crud.seleccionar(SQL.selectTodosVentasPadre(idVenta));
            if (resultado == null) {
                JOptionPane.showMessageDialog(null, "No se pudo ejecutar la consulta");
                return;
            }

            while (resultado.next()) {
                Object[] depAux = {
                    resultado.getInt(1),
                    resultado.getFloat(3),
                    resultado.getTimestamp(2)
                };
                modelo.addRow(depAux);
            }

            this.tabla_Info_ventas.setModel(modelo);

            this.txt_idVenta.setText("");

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No hay ventas con ese código");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El código de venta debe ser un número");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la consulta: " + e);
        }
    }

    private void limpiarTabla() {
        tabla_Info_ventas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));

    }

}
